---
title: "Configuración de RStudio"
output:
  html_document:
    css: !expr here::here("styles/styles.css")
    toc: true
    toc_depth:  3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("yaml.eval.expr" = TRUE)
```

# 1.3. Configuración de RStudio
Configuración de directorios de trabajo y proyectos.\  

## 1.3.1. Directorio de trabajo  
Al finalizar esta sección habrás creado un directorio de trabajo, y sabrás cómo cambiarlo.  

### Creando un Directorio de Trabajo
Preparando el lugar para futuros proyectos.  

Estamos listo/as para empezar a trabajar con RStudio, y correr códigos R, en un nuevo archivo de edición R Script.  Este nuevo archivo tiene como nombre _Untitled1_ y eventualmente debemos guardarlo con un nombre relacionado a la actividad que estemos trabajando.  Pero antes de empezar a crear y guardar archivos, debemos estar seguro/as de dónde vamos a hacerlo, para luego recuperarlos sin problema. 

En la ventana de usos múltiples (usualmente abajo, a la derecha), en la pestaña de __Files__, pueden ver el directorio que estarían usando, y generalmente es Home, que se refiere al directorio base o raíz ( _root directory_) de acuerdo a la configuración de su computadora, donde usualmente se encuentran los diversos directorios del usuario.

Mi recomendación es crear una carpeta ( _folder_) dentro de un directorio de fácil acceso (por ejemplo: MyDocuments, Documents, dependiendo del sistema operativo), pero sugiero evitar el Desktop. Pueden llamarla R simplemente o miR.

Luego de crear su carpeta de trabajo, puede guardar en ella sus archivos de trabajo relacionados a R, sin embargo, luego de terminar su trabajo en RStudio y cerrar el programa, no queda grabada la dirección de la carpeta o sub-directorio.  Esto de puede arreglar, y aqui les indico dos maneras de hacerlo:

* A. Cada vez que entren a RStudio nuevamente, ir en la parte de arriba al menú __Session__, hacer clic, y llegar a __Set Working Directory__, se abrirá un menú y harán clic en __Choose Directory__, lo cual abrirá el mapa de directorios de su computadora y deberán seleccionar el directorio creado para R, y abrirlo.  Esto lo tendrán que hacer cada vez que corran el programa nuevamente.

* B. Una manera que preserva el directorio de trabajo en la memoria del programa, es mediante las opciones globales del sistema.  Para esto deben ir al menú general y buscar __Tools__, y hacer clic en __Global Options__ (en MacOS también puedes hacerlo con el menú de __RStudio__, hacer un clic en __Preferences__), y seleccionar el ícono de __R General__.   Luego de oprimir el botón de __Browse...__, localiza la carpeta creada como directorio, y haz clic en __Apply__ y luego __OK__.  Para que esta selección entre en efecto, deben cerrar el programa y volverlo a abrir.

Luego de abrir nuevamente el programa, en la ventana de Files debe aparecer la dirección de tu directorio de trabajo, y ahora todos los archivos que guarden estarán en esa carpeta y cada vez que vuelvan a abrir RStudio los encontrarán allí.

El siguiente video muestra los pasos anteriores, pero deben tomar en cuenta las diferencias que hay de acuerdo a la computadora y sistema operativo que estén utilizando (en mi caso es una MacBookPro con macOS Mojave).

\  

<iframe width="640" height="456" frameborder="0" scrolling="no" src="https://screencast-o-matic.com/embed?sc=cYiOqLEaVB&amp;v=6&amp;ff=1&amp;title=0&amp;controls=1" allowfullscreen="true"></iframe>  

[  __Home__](https://dsfernandez.github.io/tallerR-basico/index.html)  

***  

## 1.3.2. Proyectos  
Al finalizar esta sección habrás creado un proyecto, y sabrás cómo crear otros.  

### Proyectos en RStudio  
Terminando de organizar tu directorio de trabajo.  

Una vez que contamos con un directorio de trabajo, tenemos un sitio en el cual se guardarán los archivos que estaremos creando o trayendo para trabajar proyectos con R.   Si tenemos proyectos muy diferentes (varios cursos, investigación), puede ser confuso tener todos los archivos juntos en un mismo _folder_ (nuestro directorio de trabajo).  En este caso es mejor crear proyectos para cada tipo de trabajo.

Un proyecto es simplemente un directorio de trabajo designado con un archivo _.RProj_.  Para crearlo puedes ir al menú principal y hacer clic en __File__, o en el menú de __Project__: (en el panel, arriba a la derecha), y hacer clic en __New Project__.  Cuando se abra el menú __Create Project__, seleccionar __New Directory__.   En el menú de __Project Type__, seleccionar __New Project__.   Ahora debes darle un nombre a tu nuevo proyecto, pero antes debes verificar que en el rectángulo que dice __Create project as subdirectory of:__, aparezca el directorio general que creaste anteriormente (miR, por ejemplo); si no lo es, usa __Browse__ para localizarlo y hacer que aparezca en el rectángulo.  Finalmente haz un clic en __Create Project__, y habrás creado un proyecto con nombre.  Puedes repetir este proceso para todos los proyectos que quieras.

Cuando abres un proyecto (usando __File / Open Project__ en RStudio o haciendo doble clic en el archivo .Rproj fuera de R), el directorio de trabajo se establecerá automáticamente en el directorio en el que se encuentra el archivo .RProj.

Una vez que hayas creado un nuevo proyecto R, puedes crear inmediatamente carpetas ( _folders_) en el directorio, que contendrán tu código R, archivos de datos, imágenes y otro material relevante para tu proyecto (puedes hacerlo fuera de R en tu computadora, o en la ventana de archivos (__Files__) de RStudio). Por ejemplo, podrías crear una carpeta llamada __codigo__ (no usar tildes, para evitar posibles problemas entre sistemas operativos) que contenga todo tu código R, una carpeta llamada __datos__ que contenga todos sus datos, una para __imagenes__, y otra para __referencias__.  
\

<iframe width=640 height=399 frameborder="0" scrolling="no" src="https://screencast-o-matic.com/embed?sc=cYjDr6GHSL&v=6&ff=1&title=0&controls=1" allowfullscreen="true"></iframe>

[  __Home__](https://dsfernandez.github.io/tallerR-basico/index.html)  

*** 

## 1.3.3. Paquetes  
Al finalizar esta sección podrás localizar, descargar, instalar y activar paquetes R.  

### Descarga e Instalación de Paquetes  
Los paquetes ( _packages_) añaden funcionalidades al R básico o son aplicaciones completas con sus propias funciones.  

Los paquetes R son una colección de funciones R, código compilado y datos de ejemplos. Se almacenan en un directorio llamado " _library_" en el entorno R.  Por defecto, R instala un conjunto de paquetes durante la instalación inicial. Más paquetes se agregan más tarde, cuando se necesitan para algún propósito específico. Cuando iniciamos la consola R, solo los paquetes predeterminados están disponibles por defecto. Otros paquetes que ya están instalados deben cargarse explícitamente para ser utilizados por el programa R que los va a usar.

El directorio (o directorios) en el que se encuentran los paquetes es uno especial del sistema, y podemos localizarlo con el comando:\  

__.libPaths( )__  

Dentro de este directorio se encuentran los paquetes básicos del sistema, y los que estaremos instalando, según las necesidades de cada proyecto.  Para ver que paquetes tenemos disponibles, podemos usar el comando:\  

__library( )__  

o seleccionar la pestaña __Packages__, en la ventana de usos múltiples.

Para hacer prácticamente cualquier cosa en R, podemos aprovechar algunos de los miles de paquetes adicionales disponibles para R en CRAN (Comprehensive R Archive Network).  Los paquetes se pueden instalar desde la consola de R o el editor de códigos.  El comando para instalar un paquete es:\    

__install.packages("aqui-el-nombre-del-paquete")__

Si no deseas escribir el comando, en RStudio, usamos la pestaña __Packages__, en la ventana inferior derecha; haz clic en ella y verás un botón de __Install__. (También hay un comando del menú principal en __Tools__; aunque la ubicación varía según el sistema operativo).  En estos casos, se abre una ventana en la que debemos seleccionar de donde queremos bajar o cargar el paquete, y buscarlo por su nombre.  Durante la instalación del paquete es posible que se instalen otros paquetes necesarios, o que la consola solicite decisiones sobre la instalación.

Para usar un paquete en tu proyecto, una vez que está instalado, debe activarlo, usando el siguiente comando:\

__library("nombre-del-paquete")__

Con el menú de __Packages__, puede realizar las funciones anteriores y otras relacionadas con el manejo de los paquetes.

<iframe width=640 height=408 frameborder="0" scrolling="no" src="https://screencast-o-matic.com/embed?sc=cYjDr4GJeG&v=6&ff=1&title=0&controls=1" allowfullscreen="true"></iframe>\

[  __Home__](https://dsfernandez.github.io/tallerR-basico/index.html)  







